#http://docs.travis-ci.com/user/languages/android/
language: android

sudo: false
jdk: oraclejdk8
android:
  components:
      - tools
      - platform-tools
      - build-tools-26.0.2
      - android-26
      - extra-android-support
      - extra-android-m2repository

script:
    - cp presentation/key.properties.example presentation/key.properties
    - cp presentation/key.properties.example presentation/debugkey.properties
    - keytool -genkey -v -keystore presentation/debug.keystore -alias AndroidDebugKey -keyalg RSA -keysize 2048 -validity 1 -storepass android -keypass android -dname "cn=TEST, ou=TEST, o=TEST, c=TE"
    - ./gradlew clean assemble


# reference https://docs.travis-ci.com/user/languages/android